/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as TermsRouteImport } from './app/terms'
import { Route as SignInRouteImport } from './app/sign-in'
import { Route as PrivacyRouteImport } from './app/privacy'
import { Route as AuthenticatedRouteImport } from './app/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './app/_authenticated/index'
import { Route as ApiChatsRouteImport } from './app/api/chats'
import { Route as ApiChatRouteImport } from './app/api/chat'
import { Route as ApiChatsChatIdRouteImport } from './app/api/chats/$chatId'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatsRoute = ApiChatsRouteImport.update({
  id: '/api/chats',
  path: '/api/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsChatIdRoute = ApiChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ApiChatsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chats/$chatId': typeof ApiChatsChatIdRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chats/$chatId': typeof ApiChatsChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chats/$chatId': typeof ApiChatsChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/api/chat'
    | '/api/chats'
    | '/api/auth/$'
    | '/api/chats/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/api/chat'
    | '/api/chats'
    | '/'
    | '/api/auth/$'
    | '/api/chats/$chatId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/api/chat'
    | '/api/chats'
    | '/_authenticated/'
    | '/api/auth/$'
    | '/api/chats/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatsRoute: typeof ApiChatsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chats': {
      id: '/api/chats'
      path: '/api/chats'
      fullPath: '/api/chats'
      preLoaderRoute: typeof ApiChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats/$chatId': {
      id: '/api/chats/$chatId'
      path: '/$chatId'
      fullPath: '/api/chats/$chatId'
      preLoaderRoute: typeof ApiChatsChatIdRouteImport
      parentRoute: typeof ApiChatsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiChatsRouteChildren {
  ApiChatsChatIdRoute: typeof ApiChatsChatIdRoute
}

const ApiChatsRouteChildren: ApiChatsRouteChildren = {
  ApiChatsChatIdRoute: ApiChatsChatIdRoute,
}

const ApiChatsRouteWithChildren = ApiChatsRoute._addFileChildren(
  ApiChatsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatsRoute: ApiChatsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
